### ISSUE TITLE
Link in the readme goes to a raw vignette markdown

### ISSUE THREAD

**Issue by DMSwan** [meghapsimatrix/simhelpers#1]
I dunno if there's an easy to link to the PDF instead (or maybe HTML)? You might be better off pointing people to the vignette viewer inside of R ala the Getting Started section of the readme for SingleCaseES: https://github.com/jepusto/SingleCaseES

Anyway, good luck! This is cool and I'd be happy to contribute if there's anything you want assistance on.

**Comment by meghapsimatrix** [comment]
Thanks, Danny! The vignettes aren't really ready haha - super duper underdevelopment. But will look into linking and all. Thanks for the link!
