### ISSUE TITLE
CRAN release for furrr

### ISSUE THREAD

**Issue by DavisVaughan** [meghapsimatrix/simhelpers#14]
Hi there,

I have run revdeps for furrr and your package appeared in the checks.

It seems the CRAN version of your package still uses `future_options()`. This is now defunct in furrr.

I can see that you have removed it in favor of `furrr_options()` here, which is great!
https://github.com/meghapsimatrix/simhelpers/commit/dae31e311ae13a2d4581a89edc49eb7b1b827d00

You should also remove this `@importFrom` line here:
https://github.com/meghapsimatrix/simhelpers/blob/dae31e311ae13a2d4581a89edc49eb7b1b827d00/R/evaluate_by_row.R#L32

After you do that, is there any way you can submit simhelpers to CRAN very soon? The furrr release is otherwise ready to go.

Thanks!

**Comment by DavisVaughan** [comment]
If you don't feel like you can get simhelpers out in 2 days or so, that's fine too! Just let me know and I will submit to CRAN anyways, and CRAN will give you a 2 week warning to submit a fix

**Comment by jepusto** [comment]
I'll take a look at this today. We may be able to get a CRAN submission
turned around. Will let you know by tomorrow morning if it's not in the
cards.

**Comment by jepusto** [comment]
Version 0.1.2 is on its way to CRAN.

**Comment by DavisVaughan** [comment]
Great, thank you!
