### ISSUE TITLE
Add SE as an absolute performance measure

### ISSUE THREAD

**Issue by jepusto** [meghapsimatrix/simhelpers#21]
We provide bias, variance, MSE, and RMSE, so why not true standard error also? For computing Monte Carlo standard errors, could use the same jackknife formulas as for RMSE.

**Comment by meghapsimatrix** [comment]
I am adding the true standard error to the MCSE vignette - everything else looks fine 

![image](https://github.com/meghapsimatrix/simhelpers/assets/33493716/3fae71b6-c415-40f8-ace4-64131f229ec8)

**Comment by jepusto** [comment]
Closed with #23.
