### ISSUE TITLE
sim workflow edits

### ISSUE THREAD

**Issue by meghapsimatrix** [meghapsimatrix/simhelpers#9]
What is does the ending mean here in the sim workflow edits? Should I fill in the options?

![image](https://user-images.githubusercontent.com/33493716/77584899-9d90ca00-6eb1-11ea-9f91-1dc1da94576a.png)

**Comment by jepusto** [comment]
"such as options for how estimation should be carried out (e.g., use HC0
standard errors or HC2 standard errors)."

Will this work? If so, could you add?

**Comment by meghapsimatrix** [comment]
Yeah adding now! Thanks!
